- src/components/navbar.tsx
> Initial styling for navbar

- src/components/footer.tsx
> Initial footer

- index.html
- src/components/views/cartButton.tsx
- src/components/views/lines.tsx
- src/components/views/navigationProduct.tsx
- src/components/views/pages/front.tsx
#20 komponent skapad. Har inte gått in på props eller funktioner än.
Gjorde även linjerna dynamiska
> Dynamic lines and cart button component added

- README.md
- src/components/views/pages/product.tsx
- src/data/color.tsx
- src/data/products.tsx
> Start on the product page

- src/components/interaction/inputFieldsCart.tsx
- src/components/pages/checkOut.tsx
- src/components/product/productCardCart.tsx
#6 
Added stepper to cart page and the ability to use components for different steps on checkout. 
This is only the initial design and components. 
Validation for the input fields are not yet started.
Component for "integration" and the last checkout is not started yet.
> Adding Stepper & Components for Cart

- src/components/common/sectionCartContainer.tsx
- src/components/pages/checkOut.tsx
- src/components/payment/summaryCard.tsx
- src/components/product/compareProduct.tsx
- src/components/product/productCardCart.tsx
> Added Summary component and cart styling

- src/components/admin/addProduct.tsx
- src/components/context/provider.tsx
- src/components/pages/admin.tsx
- src/components/pages/front.tsx
- src/components/product/productDetailsAdmin.tsx
- src/data/products.tsx
#10 Nu kan man skapa en produkt. Ingen validering fixad. Blir i nästa steg.
> Add Product

- src/components/interaction/inputFieldsCart.tsx
#6 
#40 
inputFieldsCart.tsx needs to be devided into components to make the file shorter.
> Validating input fields

- src/data/delivery.ts
#6 
#54 
Added data for rendering out the delivery options.
> Added data for "delivery" options

- src/components/admin/addProduct.tsx
- src/components/admin/changeProduct.tsx
- src/components/context/provider.tsx
- src/components/layout.tsx
- src/components/pages/admin.tsx
- src/components/pages/product.tsx
- src/components/product/productBanner.tsx
- src/components/product/productDetailsAdmin.tsx
- src/components/product/productIncludeCard.tsx
#10 och #11  En lättare validering med alerts bara än sålänge för att inte riskera att sidan krashar när man inte fyllt i något fält. 
+ URL-bild integrerad
> Change product

- src/components/admin/addAndModifyProduct.tsx
- src/components/admin/adminTemplatePart.tsx
- src/components/admin/modifyProduct.tsx
- src/components/contentContainer.tsx
- src/components/interaction/deleteButton.tsx
- src/components/interaction/dialogs.tsx
- src/components/interaction/inputFieldsAdmin.tsx
- src/components/pages/admin.tsx
- src/components/product/productDetailsAdmin.tsx
#10 och #11  Validering osv fixade. Kika gärna på resultatet och se om det är något jag missat på samtliga CRUD-delar :)
> validation, alerts, confirm - Admin

- src/components/context/cartProvider.tsx
- src/components/interaction/cartButton.tsx
- src/components/layout.tsx
- src/components/product/productCardCart.tsx
adding cartlist on click to localstorage and uppdates context aswell
#44
> Start logic for cart

- src/components/admin/errorHandler.tsx
- src/components/common/contentTitle.tsx
- src/components/common/lines.tsx
- src/components/context/cartProvider.tsx
- src/components/context/provider.tsx
- src/components/layout.tsx
- src/components/pages/front.tsx
- src/components/product/productCard.tsx
#47 Context skapad och kan användas. Utgick från Victors exempel.
#39 Mediaquery fixad på startsidan. Kika gärna och se om ni vill att jag ändrar något :)
> Context mediaquery + frontpage mediaquery

- src/components/admin/accordionAdmin.tsx
- src/components/admin/addAndModifyProduct.tsx
- src/components/admin/tabPanelAdmin.tsx
- src/components/pages/admin.tsx
- src/components/pages/front.tsx
- src/components/product/productDetailsAdmin.tsx
#39 Mediaquery klar på frontPage
#60 Mediaquery påbörjad på admin. Lade till en collapse i mobilt läge. Ej stylad för tillfället.
> Mediaquery

- src/components/adminParts/addAndModifyProduct.tsx
- src/components/adminParts/errorHandler.tsx
- src/components/interaction/InputFormControlAdmin.tsx
- src/components/interaction/InputFormControlCheckAdmin.tsx
- src/components/interaction/InputTextFieldsAdmin.tsx
- src/components/interaction/cartButton.tsx
- src/components/pages/front.tsx
- src/components/pages/product.tsx
- src/components/product/productBanner.tsx
- src/components/product/productCard.tsx
- src/components/product/productIncludeCard.tsx
#76 Mediaquery klar på produktsida. Checka om ni vill att jag ändrar något eller om jag missat något :)
> Mediaquery productpage

- src/components/payment/cartSummary.tsx
- src/components/payment/paymentOptions.tsx
- src/data/paymentOptions.ts
> Input fields validation

- src/components/adminParts/addAndModifyProduct.tsx
- src/components/common/contentTitle.tsx
- src/components/context/cartProvider.tsx
- src/components/context/provider.tsx
- src/components/interaction/InputFormControlAdmin.tsx
- src/components/interaction/InputFormControlCheckAdmin.tsx
- src/components/interaction/InputTextFieldsAdmin.tsx
- src/components/interaction/cartButton.tsx
- src/components/pages/front.tsx
- src/components/product/cartSelectedItem.tsx
- src/components/product/productBanner.tsx
- src/components/product/productCardCart.tsx
- src/data/products.tsx
> Cleaning up

- src/components/context/deliveryProvider.tsx
- src/components/payment/delivery.tsx
- src/components/payment/summaryCard.tsx
#89 
#90 
Added initial functionality for validating steps before continuing. 
Added context for delivery option.
> Added context for delivery

- src/components/pages/checkOut.tsx
#6 
Added ability to navigate through an earlier step on the cart page when clicking the stepper.
> added ability to navigate through the steps

- src/data/paymentOptions.ts
> Added the ability to pay via invoice.

- src/components/payment/cartSummary.tsx
- src/components/payment/paymentOptions.tsx
> Checking if inputData.input & not rendering empty

- src/components/context/checkOutProvider.tsx
- src/components/layout.tsx
- src/components/payment/paymentOptions.tsx
#6 
#102
Added context to save the values of the input fields on check out.
> Added context to checkout fields

- src/components/interaction/paymentOptionsErrorHandler.tsx
- src/components/payment/paymentOptions.tsx
- src/components/payment/summaryCard.tsx
- src/data/paymentOptions.ts
#6 
#103 
#104 
Validating the check out fields through the stepper. 
Added ability to autofill card and phone.
> Checkout validation on stepper

- src/components/payment/delivery.tsx
- src/data/delivery.ts
#6
#110 
Added delivery date to the different delivery options.
> Added delivery date

- src/components/common/sectionCartContainer.tsx
- src/components/pages/checkOut.tsx
- src/components/payment/cartSummary.tsx
- src/components/payment/delivery.tsx
- src/components/payment/paymentOptions.tsx
- src/components/payment/summaryCard.tsx
- src/components/product/cartOptions.tsx
- src/components/product/cartSelectedItem.tsx
- src/components/product/productCardCart.tsx
- src/data/color.tsx
> summary price func and styling

- index.html
- src/components/adminParts/addAndModifyProduct.tsx
- src/components/common/navbar.tsx
- src/components/context/cartProvider.tsx
- src/components/interaction/InputFormControlCheckAdmin.tsx
- src/components/interaction/cartButton.tsx
- src/components/pages/checkOut.tsx
- src/components/pages/confirmation.tsx
- src/components/pages/front.tsx
- src/components/payment/cartSummary.tsx
- src/components/payment/summaryCard.tsx
- src/components/product/cartOptions.tsx
- src/components/product/compareProduct.tsx
- src/data/products.tsx
- src/data/products_old.tsx
#121 
#114 
#118  Påbörjad. Skall mergas ihop med Freddans kod =) 
#115 Påbörjad. Skal kolla upp MUIs  modalfönster istället för att få en bättre lösning
> Confirmation

- src/components/pages/confirmation.tsx
- src/components/payment/priceLogic.tsx
- src/components/payment/summaryCard.tsx
- src/components/product/cartSelectedItem.tsx
> priceSummaryFunc

- src/components/interaction/confirmation.tsx
miniändring - height på confirm
> fixed height on orderconfirmation

- src/components/interaction/confirmation.tsx
- src/components/interaction/inputFieldsCart.tsx
- src/components/pages/checkOut.tsx
- src/components/payment/delivery.tsx
- src/components/product/cartSelectedItem.tsx
> Added remove from cart button

- src/components/adminParts/tabPanelAdmin.tsx
- src/components/common/contentTitle.tsx
- src/components/common/footer.tsx
- src/components/common/navbar.tsx
- src/components/common/scrollToTop.tsx
- src/components/common/sectionCartContainer.tsx
- src/components/context/deliveryProvider.tsx
- src/components/context/invoiceProvider.tsx
- src/components/interaction/cartButton.tsx
- src/components/interaction/dialogs.tsx
- src/components/interaction/inputFieldsCart.tsx
- src/components/interaction/paymentOptionsErrorHandler.tsx
- src/components/pages/checkOut.tsx
- src/components/pages/front.tsx
- src/components/pages/product.tsx
- src/components/payment/cartSummary.tsx
- src/components/payment/delivery.tsx
- src/components/payment/priceLogic.tsx
- src/components/payment/summaryCard.tsx
- src/components/product/cartOptions.tsx
- src/components/product/cartSelectedItem.tsx
- src/components/product/compareProduct.tsx
- src/components/product/productBanner.tsx
- src/components/product/productCard.tsx
- src/components/product/productCardCart.tsx
- src/components/product/productIncludeCard.tsx
> Remove unused imports
